### ISSUE TITLE
Knit the .Rmd into an .html to provide as website.

### ISSUE THREAD

**Issue by krshedd** [commfish/Biometric_Best_Practices#2]
Hi Ben,
I would recommend kniting your `best_practices.Rmd` to an .html file and changing the *Settings* for the repository to turn on GitHub pages for the `master` branch. Once you push the `best_practices.html` to `master` it should be publicly accessible via GitHub Pages as it's own [link](https://commfish.github.io/Biometric_Best_Practices/best_practices.html). We learned about this from the Reproducible Research folks at NCEAS this week in Juneau. Here is a [link](https://nceas.github.io/sasap-training/materials/reproducible-analysis-in-r/publishing-analyses-to-the-web.html#a-minimal-example) to their example of this process.
Cheers,
Kyle

**Comment by ben-williams** [comment]
Appreciate the input. I've been using the pages for a few  - see http://ben-williams.github.io/updated_ggplot_figures.html 

There are a few items I would like to clean up before creating a stand alone page - but happy someone is looking at it!

**Comment by krshedd** [comment]
Awesome, thanks. Your ggplot figure page is really cool. Thanks for moving all of this forward.

**Comment by ben-williams** [comment]
actually i lied - you had a good idea I post it up!
